In [ ]:
c(1,2,3,4,5)

[1] 1 2 3 4 5

In [ ]:
head(iris,3)

Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1 5.1          3.5         1.4          0.2         setosa 
2 4.9          3.0         1.4          0.2         setosa 
3 4.7          3.2         1.3          0.2         setosa

In [ ]:
#주석...프로그램해석안함/
#사람을 위한것임 
#프로그램 설명 
a=10;
b=20

In [ ]:
print(a);print(b)


[1] 10
[1] 20


In [ ]:
2**3
2^3 #캐럿
10/3
10%/%3
10%%3

[1] 8

[1] 8

[1] 3.333333

[1] 3

[1] 1

In [ ]:
a=10
b<-20
30->c
a+b+c

[1] 60

In [ ]:
v1 = c(1,2,3,4,5)
sum(v1)

[1] 15

In [ ]:
sum(v3 <- c(1,2,3,4,5))

[1] 15

In [ ]:
v3

[1] 1 2 3 4 5

In [ ]:
a=10
b=20
a==b
a!=b
!(a==b)
a >= b 

[1] FALSE

[1] TRUE

[1] TRUE

[1] FALSE

In [ ]:
a=10
b=20

#&&, & : 모두 true이면 true이다. 
# && : 앞의 결과가 거짓이면 뒤문장 수행안함 
# & : 앞의 결과 상관없이 끝까지 수행 
a<10 && (b<-b+1)>=20

a<10 & (b<-b+1)>=20


[1] FALSE

[1] FALSE

In [ ]:
b

[1] 21

In [ ]:
#||, | : 하나라도  true이면 true이다. 
# || : 앞의 결과가 참이면 뒤문장 수행안함 
# | : 앞의 결과 상관없이 끝까지 수행 
a=10
b=20
a>=10 || (b<-b+1)>=20
b
a>=10 | (b<-b+1)>=20
b

[1] TRUE

[1] 20

[1] TRUE

[1] 21

In [ ]:
a=10  #실수가 기본이다.
a2=10L #정수 
b="문자"
c='문자'
d=10>20
e=1+2i
typeof(a)
typeof(a2)
typeof(b)
typeof(c)
typeof(d)
typeof(e)


[1] "double"

[1] "integer"

[1] "character"

[1] "character"

[1] "logical"

[1] "complex"

In [ ]:
#값이없음 
a = NULL
#있어야하는데 빠짐..결측
b = NA
#NaN (Not a NUmber)
sqrt(-3)

Warning message in sqrt(-3):
“NaNs produced”


[1] NaN

In [ ]:
a=10
a2=20L
b="문자"
mode(a); typeof(a); class(a)
mode(a2); typeof(a2); class(a2)
mode(b); typeof(b); class(b)
mode(c); typeof(c); class(c)
mode(d); typeof(d); class(d)
mode(e); typeof(e); class(e)

[1] "numeric"

[1] "double"

[1] "numeric"

[1] "numeric"

[1] "integer"

[1] "integer"

[1] "character"

[1] "character"

[1] "character"

[1] "character"

[1] "character"

[1] "character"

[1] "logical"

[1] "logical"

[1] "logical"

[1] "complex"

[1] "complex"

[1] "complex"

In [ ]:
typeof(iris)
mode(iris)
class(iris)

[1] "list"

[1] "list"

[1] "data.frame"

In [ ]:
a=10L
is.numeric(a)
is.double(a)
is.integer(a)

[1] TRUE

[1] FALSE

[1] TRUE

In [ ]:
#벡터 : 같은 타입의 하나이상의 데이타들
a=c(10,20,30,40,"50")
a=c(1,2,3,1>2, FALSE, TRUE)
a

[1] 1 2 3 0 0 1

In [ ]:
a="100"
as.numeric(a) + 200

[1] 300

In [ ]:
a = c(100,50,80,70, 99)
b = 1:10
c = 10:1
d = -3.3:2
d = -3:2

d = seq(from=1,to=10,by=2)
d = seq(from=1,by=2,to=10)
d = seq(1,10,2)
d = sequence(10)
d = seq(1,10,1)
d = 1:10
d = c(1,2,3,4,5,6,7,8,9,10)
d

[1]  1  2  3  4  5  6  7  8  9 10

In [ ]:
v1 = rep(5, times=3)
v1 = rep("R", times=3)
v1 = rep(c("R","Python"), times=3)
v1 = rep(c("R","Python"), each=3)
v1 = rep(c("R","Python"), times=2, each=3)
v1 = rep(c("R","Python"), times=c(5,2) )
v1

[1] "R"      "R"      "R"      "R"      "R"      "Python" "Python"

In [ ]:
mode(v1)
class(v1)
typeof(v1)
is.character(v1)
length(v1)

[1] "character"

[1] "character"

[1] "character"

[1] TRUE

[1] 7

In [ ]:
names(v1)

NULL

In [ ]:
names(v1) = c("A","B","C","D","E","F","G")
names(v1)
v1

[1] "A" "B" "C" "D" "E" "F" "G"

A        B        C        D        E        F        G 
     "R"      "R"      "R"      "R"      "R" "Python" "Python"

In [ ]:
#순서 : R은 1부터 시작한다. 
v1[1]
#이름으로 접근가능 
v1["A"]

v1[c(1,2,3)]
v1[seq(1,3,1)]
v1[sequence(3)]
v1[1:3]

v1[-c(1,2,3,4,5)]


A 
"R"

A 
"R"

A   B   C 
"R" "R" "R"

A   B   C 
"R" "R" "R"

A   B   C 
"R" "R" "R"

A   B   C 
"R" "R" "R"

F        G 
"Python" "Python"

In [ ]:
v1

A        B        C        D        E        F        G 
     "R"      "R"      "R"      "R"      "R" "Python" "Python"

In [ ]:
weight = c(57,81,65,49,72)
weight[1]
weight[c(1,4,5)]
weight[2:4]  #2<=  <=4
weight[-c(1,4,5)]

[1] 57

[1] 57 49 72

[1] 81 65 49

[1] 81 65

In [ ]:
v1 = c(1,2,3,4,5)
v2 = c(10,20,30,40,50)
v1+ v2
v1* v2

[1] 11 22 33 44 55

[1]  10  40  90 160 250

In [ ]:
#벡터의 개수가 다른경우는 recycling rule적용
#경고출력

v1 = c(1,2,3,4,5)
v2 = c(10,20,30) #10,20,30,10,20
v1+ v2

Warning message in v1 + v2:
“longer object length is not a multiple of shorter object length”


[1] 11 22 33 14 25

In [ ]:
v1 = 1:3  #1,2,3,1,2,3
v2 = 1:6  #1,2,3,4,5,6 
v1 + v2

[1] 2 4 6 5 7 9

In [ ]:
#levels : 있을수있는 값의 종류 , 한정적인 값의  나열 
gender = c("m","m","f","m","f")
gender_f = factor(gender) #default ..level순서는 알파벳순서 
gender_f = factor(gender, levels = c('m','f'))
gender_f = factor(gender, levels = c('m','f'), 
                          labels = c('남자','여자'))
gender_f = factor(gender, levels = c('m','f'), 
                          labels = c('남자','여자'),ordered=TRUE)
gender_f

[1] 남자 남자 여자 남자 여자
Levels: 남자 < 여자

In [ ]:
v1 = 1:3
v2 = 4:6
m1 = rbind(v1, v2)
m2 = cbind(v1, v2)
m2

v1 v2
[1,] 1  4 
[2,] 2  5 
[3,] 3  6

In [ ]:
#칼럼우선
m3= matrix(1:6, nrow = 2, ncol = 3)#byrow = FALSE
#row우선
m3= matrix(1:6, nrow = 2, ncol = 3, byrow = TRUE)
m3

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

In [ ]:
#1차원
a1 = array(1:10, dim=10)
a1 = array(1:10, dim=c(2,5) )
a1 = array(1:12, dim=c(2,3,2) )
a1

, , 1

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6

, , 2

     [,1] [,2] [,3]
[1,]    7    9   11
[2,]    8   10   12

In [ ]:
a=10
b=c(1,2,3,4,5)
c=10:15
d = matrix(1:10, nrow=2, ncol=5)
e = array(1:10, dim=c(2,3))

f = list(a,b,c,d,e)
typeof(f[1])
typeof(f[[1]])
f[[1]]

typeof(f[2])
typeof(f[[2]])

[1] "list"

[1] "double"

[1] 10

[1] "list"

[1] "double"

In [ ]:
f[[2]][5]

[1] 5

In [ ]:
typeof(f[[4]])
f[[4]][1,4]

[1] "integer"

[1] 7

In [ ]:
f[[4]]

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10